source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

def target_pods
    pod 'GreedTimer', :path => '../'
    pod 'Masonry'
end

target 'GreedTimer_Example', :exclusive => true do
    target_pods
end

target 'GreedTimer_Tests', :exclusive => true do
    target_pods
end
